### ISSUE TITLE
On InputPasswordScreen completion, show GameSettingsScreen 

### ISSUE THREAD

**Issue by nickmeinhold** [tamari-gray/niira#57]
Add UI: 
- [x] 'drag boundary' text => "move map to reposition boundary"
- [x] boundary size slider -> sets the boundary size, which updates the boundary on the map 
- [x] sonar intervals slider -> sets the sonar value, shown in slider 

- [x] add a cancel button in app bar -> pops back to Lobby 
- [x] Next fab -> navigates to waitingScreen
- [x] make user icon size relative to camera zoom

### todo:
- [x] test using gameService as changenotifierProvider and using that as state

![create a game - 3](https://user-images.githubusercontent.com/49229277/91065823-49625f80-e674-11ea-861a-69c465d505f3.png)

![create a game - 3 – 4](https://user-images.githubusercontent.com/49229277/91065818-48c9c900-e674-11ea-9520-3c02f2931c66.png)

**Comment by tamari-gray** [comment]
ithis issue is blocked by #134
